[package]
name = "cloudflare_r2"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["full"] }
aws-sdk-s3 = "1"
aws-config = { version = "1", features = ["behavior-version-latest"] }
anyhow = "1"
mime_guess = "2"
dotenvy = "0.15"
aws-smithy-types = "1.6.1"
hostname = "0.4.2"
