/*!
 * mastodon_cli — A simple Mastodon CLI for Rust learners
 *
 * WORKFLOW OVERVIEW:
 * 1. Argument Parsing: `clap` parses CLI flags into `cli::Args`.
 * 2. Configuration Resolution: token and instance are resolved from
 *    flag → env var → default (see `resolve_instance` and token logic).
 * 3. Async Runtime: `tokio` runs the `async` networking code.
 * 4. Branching: if `--message` is present we POST a new status,
 *    otherwise we GET recent statuses and pretty-print them.
 * 5. Response Handling: check HTTP status, print success or error.
 *
 * PROJECT STRUCTURE:
 * - `cli.rs`    — CLI argument definitions (clap)
 * - `api.rs`    — Mastodon API types + URL helpers + media upload
 * - `format.rs` — HTML cleaning, emoji expansion, text wrapping, box rendering
 * - `main.rs`   — glue code: config, branching, HTTP orchestration
 *
 * LIBRARIES USED:
 * - `clap` (derive): declarative CLI parsing.
 * - `reqwest`: async HTTP client (needs `tokio` to run).
 * - `tokio`: async runtime — provides the executor for `Future`s.
 * - `serde`/`serde_json`: struct ↔ JSON conversion.
 * - `regex` + `emojis`: shortcode → emoji replacement.
 * - `html-escape`: decode `&amp;` etc.
 * - `unicode-width`: correct terminal column width for emojis/CJK.
 */

// Declare sub-modules — each corresponds to a file in `src/*.rs`.
// `mod` tells the compiler to load and compile those files as part of the crate.
mod api;
mod cli;
mod format;

// Bring names into scope for ergonomic use in this file.
// `use api::{api_url, Account, ...}` avoids writing `api::api_url` everywhere.
use api::{api_url, Account, Status, StatusRequest};
use clap::Parser; // brings `Args::parse()` into scope — `Parser` is a trait
use cli::Args;
use format::replace_emojis;
use reqwest::header::{AUTHORIZATION, CONTENT_TYPE};

/// Default Mastodon instance when the user provides no `--instance` and no
/// `MASTODON_INSTANCE` env var. Keeping this as a `const` makes it easy to
/// find and change in one place.
const DEFAULT_INSTANCE: &str = "https://mastodon.social";

/// Resolves the Mastodon instance URL from (in priority order):
/// 1. `--instance` flag (`arg`)
/// 2. `MASTODON_INSTANCE` environment variable
/// 3. `DEFAULT_INSTANCE` constant
///
/// Learner notes:
/// - `Option<String>` represents "maybe a value". `None` means not provided.
/// - `or_else(|| ...)` lazily evaluates the fallback only if `arg` is `None`.
///   The closure `|| ...` is a zero-argument anonymous function.
/// - `std::env::var` reads an env var and returns `Result<String, VarError>`;
///   `.ok()` turns that into `Option<String>` (discarding the error).
/// - `unwrap_or_else` provides the final default if both flag and env are missing.
/// - We normalize the result via `api::normalize_instance` to handle
///   `mastodon.social` vs `https://mastodon.social/` consistently.
fn resolve_instance(arg: Option<String>) -> String {
    let configured = arg
        .or_else(|| std::env::var("MASTODON_INSTANCE").ok())
        .unwrap_or_else(|| DEFAULT_INSTANCE.to_string());
    api::normalize_instance(&configured)
}

/// Program entry point.
///
/// `#[tokio::main]` is a macro that:
/// 1. Creates a `tokio` async runtime (thread pool + reactor).
/// 2. Transforms this `async fn main` into a synchronous `fn main` that
///    blocks on the future. Without it, `await` would not work.
///
/// Return type `Result<(), Box<dyn std::error::Error>>` means:
/// - `Ok(())` → success, exit code 0
/// - `Err(...)` → error printed by the runtime, exit code 1
/// `Box<dyn Error>` is a type-erased error — it can hold any error type.
/// For a larger app you'd use `anyhow::Result` or a custom error enum.
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // --- 1. Parse CLI arguments ---
    // `Args::parse()` is generated by `#[derive(Parser)]` on `cli::Args`.
    // It reads `std::env::args()`, validates them (e.g. `list` range 1..=40),
    // and prints `--help` / error messages automatically on failure.
    let args = Args::parse();

    // --- 2. Resolve authentication token ---
    // Priority: `--token` flag > `MASTODON_TOKEN` env var > error.
    // `ok_or(...)` turns `Option<String>` into `Result<String, &str>` so we can
    // use `?` to propagate the error if neither is present.
    let token = args
        .token
        .or_else(|| std::env::var("MASTODON_TOKEN").ok())
        .ok_or("Mastodon token not provided. Please use --token or set MASTODON_TOKEN env var.")?;

    // --- 3. Resolve instance URL ---
    // Same priority pattern as token, but with a default fallback.
    let instance = resolve_instance(args.instance);

    // --- 4. Create a reusable HTTP client ---
    // `reqwest::Client` holds a connection pool internally. Creating one and
    // reusing it for all requests is more efficient than `reqwest::get` per call.
    let client = reqwest::Client::new();
    // Pre-format the auth header value — reused for every request.
    let auth_header = format!("Bearer {token}");

    // --- 5. Branch: POST (message provided) vs GET (list recent statuses) ---
    if let Some(msg) = args.message {
        // ===================== CASE 1: Post a new status =====================

        // Optional: upload an image first. The Mastodon API requires a two-step
        // process: 1) POST /api/v1/media → get media ID, 2) POST /api/v1/statuses
        // with that ID. `upload_media` is `async` so we `.await` it.
        let mut media_ids = None;
        if let Some(image_path) = &args.image {
            // `&args.image` borrows the Option without moving it; `&image_path`
            // is `&String`. The `println!` uses inline format `{image_path}`.
            println!("Uploading image: {image_path}...");
            let media_id = api::upload_media(&client, &token, &instance, image_path).await?;
            media_ids = Some(vec![media_id]);
            println!("Image uploaded successfully.");
        }

        // Build the JSON body. `replace_emojis` expands `:rocket:` → 🚀 before
        // sending, so the server stores actual Unicode.
        let body = StatusRequest {
            status: replace_emojis(&msg),
            media_ids,
        };

        // Send the POST request. `.json(&body)` serializes `StatusRequest` via
        // `serde` and sets `Content-Type: application/json` automatically, but
        // we also set it explicitly for clarity. `.send().await` does the I/O.
        let response = client
            .post(api_url(&instance, "/api/v1/statuses"))
            .header(AUTHORIZATION, &auth_header)
            .header(CONTENT_TYPE, "application/json")
            .json(&body)
            .send()
            .await?;

        // `is_success()` checks for 2xx status codes. On failure we print the
        // response body (which often contains a JSON error message) and exit(1)
        // so the shell sees a non-zero exit code.
        if response.status().is_success() {
            println!("Successfully posted message to Mastodon!");
        } else {
            let status = response.status();
            let error_text = response.text().await?;
            eprintln!("Error posting message: {status} - {error_text}");
            std::process::exit(1);
        }
    } else {
        // ===================== CASE 2: List recent statuses =====================

        // Step 1: Verify credentials → get our account ID.
        // `GET /api/v1/accounts/verify_credentials` returns the authenticated
        // account. We need its `id` to fetch its statuses.
        let account_resp = client
            .get(api_url(&instance, "/api/v1/accounts/verify_credentials"))
            .header(AUTHORIZATION, &auth_header)
            .send()
            .await?;
        if !account_resp.status().is_success() {
            let status = account_resp.status();
            let error_text = account_resp.text().await?;
            eprintln!("Error verifying credentials: {status} - {error_text}");
            std::process::exit(1);
        }
        // `.json::<Account>().await` deserializes the JSON body into our struct.
        // The `::Account` turbofish tells the compiler which type to deserialize.
        let account_id = account_resp.json::<Account>().await?.id;

        // Step 2: Fetch recent statuses for that account.
        // `args.list` is validated by clap (1..=40), safe to interpolate.
        let statuses_url = api_url(
            &instance,
            &format!("/api/v1/accounts/{account_id}/statuses?limit={}", args.list),
        );
        let statuses_resp = client
            .get(statuses_url)
            .header(AUTHORIZATION, &auth_header)
            .send()
            .await?;
        if !statuses_resp.status().is_success() {
            let status = statuses_resp.status();
            let error_text = statuses_resp.text().await?;
            eprintln!("Error fetching statuses: {status} - {error_text}");
            std::process::exit(1);
        }

        // Parse the JSON array into `Vec<Status>`.
        let statuses = statuses_resp.json::<Vec<Status>>().await?;
        if statuses.is_empty() {
            println!("No recent statuses found.");
        } else {
            println!("Recent {} statuses:\n", args.list);
            // `.iter().enumerate()` yields `(index, &Status)` — index is 0-based,
            // so `format_status` adds 1 for display.
            for (i, status) in statuses.iter().enumerate() {
                println!("{}\n", format::format_status(i, status));
            }
        }
    }
    // `Ok(())` signals success to the `tokio` runtime.
    Ok(())
}

#[cfg(test)]
mod tests {
    // `#[cfg(test)]` means this module is only compiled when running `cargo test`.
    // It is not included in the release binary.
    use super::*;

    #[test]
    fn normalizes_default_instance() {
        // Bare hostname with trailing slash → adds https:// and strips slash
        assert_eq!(
            api::normalize_instance("mastodon.social/"),
            "https://mastodon.social"
        );
        // Full URL with trailing slash → just strips slash, keeps scheme
        assert_eq!(
            api_url("https://example.social/", "/api/v1/statuses"),
            "https://example.social/api/v1/statuses"
        );
    }
}
